FROM openjdk:11
MAINTAINER danhull@gmail.com
COPY planets-0.0.1-SNAPSHOT.jar /usr/src/planets.jar
#COPY entrypoint.sh /opt/spring-cloud/bin/
#ENTRYPOINT ["/usr/bin/java"]
#CMD ["-jar", "/opt/spring-cloud/lib/planets.jar"]
EXPOSE 8888